[project]
name = "effev"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "esm>=3.2.3",
    "fair-esm>=2.0.0",
    "numpy>=2.4.2",
    "scipy>=1.17.0",
    "torch>=2.10.0",
    "torch-scatter>=2.1.2",
]

[tool.uv]
no-build-isolation-package = [ "torch_scatter" ]
